### PR TITLE
Retry failed services

### LINKED ISSUE #520: How to handle downstream/network errors on gateway initialization?
I have encountered the scenario that federated services may not be up yet when the gateway has initialized. In this case, the gateway will not retry polling those services in question. It's a different behavior as opposed to when everything (all services, the gateway) is up and running and, say, one of the federated services goes down. In this case, the gateway will retry polling that service according to the set 'polling'-interval. This is what I  would also expect on errors with non-ready federated services on gateway startup.

Is this a scenario overlooked in the polling mechanism or is it my task to handle this error? If the latter, how would I ask the gateway to retry connection/polling to the service in question in the errorHandler? The example in the docs only shows simple error logging but how could I actually address the problem?

The workaround right now is to restart the gateway when all federated services are up and running. This is fine for development but I would rather make sure the gateway always retries reaching out to the configured services on gateway startup errors.

Greets
-act

### PR DESCRIPTION
**Pull request by sameer-coder**
This PR adds functionality to retry any services that might have failed or are slow to start when mercurius starts up in gateway mode. At the moment I have hardcoded the timer to be 1 second but we can change it to a whatever seems appropriate.

Open to any feedback to improve the implementation.

Closes #520

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
I think we should have a limit on how many times a failed service could be retried.
I would prefer the logic to be separated from the `gatewayInterval` timer because I do not want the gateway to "become ready" if there are failed services that are `mandatory`.

If there are services that are not `mandatory` then we can go ahead without them (and not retry, there is the polling interval for those).

**Comment by sameer-coder** [comment]
The CI is failing due to coverage being less than 100. I will am working on updating the tests.

File: index.js [hunk 1]
```diff
@@ -175,9 +175,50 @@ const plugin = fp(async function (app, opts) {
...
+          // Trigger onGatewayReplaceSchema hook
+          if (context.onGatewayReplaceSchema !== null) {
+            await onGatewayReplaceSchemaHandler(context, { instance: app, schema })
+          }
+          fastifyGraphQl.replaceSchema(schema)
+        }
+      }, interval)
+    } catch (error) {
+      app.log.error(error)
+    }
```
Comment (mcollina) [inline index.js:207]: This creates a memory leak in case of an error. Move the try catch inside the setInterval function.

File: lib/gateway/service-map.js [hunk 2]
```diff
@@ -201,7 +201,7 @@ async function buildServiceMap (services, errorHandler) {
       serviceConfig = await serviceMap[service.name].init()
     } catch (err) {
       serviceConfigErr = err
-      errorHandler(err, service)
+      if (!service.mandatory) errorHandler(err, service)
```
Comment (mcollina) [inline lib/gateway/service-map.js:204]: we should probably log if it's not mandatory

File: test/gateway/schema.js [hunk 3]
```diff
@@ -2385,7 +2385,7 @@ test('Update the schema', async (t) => {
   gateway.graphql.gateway.serviceMap.working.setSchema(fullSchema)
   const newSchema = await gateway.graphql.gateway.refresh()
 
-  gateway.graphql.replaceSchema(newSchema)
+  gateway.graphql.replaceSchema(newSchema.schema)
```
Comment (mcollina) [inline test/gateway/schema.js:2388]: why this change?

File: lib/gateway.js [hunk 4]
```diff
@@ -379,19 +379,27 @@ async function buildGateway (gatewayOpts, app) {
     serviceMap,
     entityResolversFactory: factory,
     pollingInterval: gatewayOpts.pollingInterval,
-    async refresh () {
+    async refresh (shouldRetry) {
```
Comment (mcollina) [inline lib/gateway.js:382]: I don't understand the naming of this parameter

**Review by mcollina — CHANGES_REQUESTED** [review]

File: test/gateway/schema.js (hunk 3 above)
Comment (sameer-coder) [reply test/gateway/schema.js:2388]: the `gateway.refresh()` function now returns an object `{ schema, failedServices }` instead of only the `schema` which is why I had to change this.

File: lib/gateway.js (hunk 4 above)
Comment (sameer-coder) [reply lib/gateway.js:382]: It's a boolean parameter which specified if the retries should be done or not. should I change it to something like `isRetry`?

File: lib/gateway/service-map.js (hunk 2 above)
Comment (sameer-coder) [reply lib/gateway/service-map.js:204]: Ok I will add a logline before calling the error handler for non mandatory services

File: test/gateway/schema.js (hunk 3 above)
Comment (mcollina) [reply test/gateway/schema.js:2388]: Unfortunately this would be a semver-major change that I would like to avoid. Can you rearrange the API differently?

**Review by mcollina — CHANGES_REQUESTED** [review]

**Comment by sameer-coder** [comment]
@mcollina There are quite a few polling related tests failing. I am trying to find what the issue is and will update the PR soon.

File: index.js [hunk 5]
```diff
@@ -175,9 +175,49 @@ const plugin = fp(async function (app, opts) {
...
   let entityResolversFactory
+  let gatewayRetryIntervalTimer = null
+
+  const retryServices = (interval) => {
+    let retryCount = 0
+    let isRetry = true
+
+    return setInterval(async () => {
+      try {
+        if (retryCount === 10) isRetry = false
```
Comment (jonnydgreen) [inline index.js:186]: should we make this configurable?

File: index.js [hunk 6]
```diff
@@ -175,9 +175,49 @@ const plugin = fp(async function (app, opts) {
...
+    }, interval)
+  }
+
   if (gateway) {
     gateway = await buildGateway(gateway, app)
 
+    const serviceMap = Object.values(gateway.serviceMap)
+    const failedMandatoryServices = serviceMap.filter(service => !!service.error && service.mandatory)
+
+    const retryInterval = 3000
```
Comment (jonnydgreen) [inline index.js:215]: should we make this configurable?

**Review by jonnydgreen — COMMENTED** [review]
It would be great to include some documentation on this retry flow as well

File: index.js (hunk 5 above)
Comment (mcollina) [reply index.js:186]: I think it would be a good idea

File: index.js (hunk 6 above)
Comment (mcollina) [reply index.js:215]: I think it would be a good idea

File: index.js (hunk 5 above)
Comment (sameer-coder) [reply index.js:186]: cool. I will make it configurable.

**Comment by sameer-coder** [comment]
When I run the tests on my local machine they are all passing. I am not sure what's wrong but I think one of the timer related tests  fails 1 out of 5 times.

File: test/gateway/retry-failed-services.js [hunk 7]
```diff
@@ -0,0 +1,513 @@
...
+      {
+        message: 'Cannot query field "posts" on type "User".',
+        locations: [{ line: 6, column: 9 }]
+      }
+    ],
+    data: null
+  })
+})
+
+test('gateway - stop retrying after no. of retries exceeded', async (t) => {
```
Comment (sameer-coder) [inline test/gateway/retry-failed-services.js:400]: I guess this is the problematic test which is failing the CI at times

Comment (jonnydgreen) [reply test/gateway/retry-failed-services.js:400]: From past experience, it could be related to the hardcoding of the port to 500(1|2) in the tests if it's failing intermittently in the CI. I would suggest passing `0` to `.listen()` if you can. If you need access to the port for use in the gateway config, you could listen straightaway and trigger errors dynamically using hooks (there are alternative methods, for sure! :) ). As an example:

```js
let shouldError = true
const service2 = await createTestService(postService.schema, postService.resolvers)
service2.addHook('onRequest', async () => {
  if (shouldError) {
    throw new Error('kaboom')
  }
})
await service2.listen(0)

// some work ...

shouldError = false
```

Comment (jonnydgreen) [reply test/gateway/retry-failed-services.js:400]: Any luck on this? I'm available to help debug this, this week, if you need :)

Comment (sameer-coder) [reply test/gateway/retry-failed-services.js:400]: Thanks a lot @jonnydgreen  No luck so far. I tried the way you suggested but the tests are still failing. Seems the problem lies elsewhere. I am working on this today and will dig deeper. I will provide an update soon. Thanks!

Comment (jonnydgreen) [reply test/gateway/retry-failed-services.js]: Awesome, sounds good!

**Comment by mcollina** [comment]
@jonnydgreen can you do a final check?

**Comment by sameer-coder** [comment]
@jonnydgreen Would appreciate if you could run the tests once just to make sure that the issue with tests has been resolved. Thanks.

File: lib/gateway.js [hunk 8]
```diff
@@ -446,7 +460,7 @@ async function buildGateway (gatewayOpts, app) {
 
       defineResolvers(schema, typeToServiceMap, serviceMap, typeFieldsToService)
 
-      return schema
+      return { schema, failedMandatoryServices }
```
Comment (jonnydgreen) [inline lib/gateway.js:463]: I'm guessing this will be a semver major change? We should update the typings (with type tests) as well: https://github.com/mercurius-js/mercurius/blob/6943453acd1f0bc1787d1b23695230227e890c58/index.d.ts#L230

**Review by jonnydgreen — COMMENTED** [review]
Functionally all good - just a comment on the typings to be updated for the `.refresh` return value

File: lib/gateway.js [hunk 9]
```diff
@@ -379,19 +379,33 @@ async function buildGateway (gatewayOpts, app) {
...
+            // failedMandatoryServices so it can be returned for retrying
+            if (service.mandatory) {
+              failedMandatoryServices.push(service)
+            }
           })
         )
       )
 
+      if (failedMandatoryServices.length > 0) {
+        return { schema: null, failedMandatoryServices }
```
Comment (mcollina) [inline lib/gateway.js:406]: Can you please avoid this breaking change? Instead of chancing the return type, you can throw an error here.

File: lib/gateway.js (hunk 8 above)
Comment (mcollina) [reply lib/gateway.js:463]: It's better to avoid the breaking change.

**Review by mcollina — CHANGES_REQUESTED** [review]

**Comment by sameer-coder** [comment]
I've updated the code so that it's no longer a breaking change

File: index.d.ts [hunk 10]
```diff
@@ -227,7 +227,7 @@ interface ServiceConfig {
 }
 
 interface Gateway {
-  refresh: () => Promise<GraphQLSchema | null>;
+  refresh: (isRetry: boolean) => Promise<GraphQLSchema | null>;
```
Comment (jonnydgreen) [inline index.d.ts:230]: I would say this is still a breaking change from a type PoV since the current type tests won't pass with this change (we can no longer call `.refresh()` without compilation errors in TypeScript). Can we make the input optional?

Comment (sameer-coder) [reply index.d.ts:230]: Sorry, I didn't notice that. The input is optional. I will change it to `refresh: (isRetry?: boolean)`

Comment (sameer-coder) [reply index.d.ts]: I have changed it. I think the PR should be ready now.

File: lib/gateway.js [hunk 11]
```diff
@@ -379,19 +379,33 @@ async function buildGateway (gatewayOpts, app) {
...
+            // failedMandatoryServices so it can be returned for retrying
+            if (service.mandatory) {
+              failedMandatoryServices.push(service)
+            }
           })
         )
       )
 
+      if (failedMandatoryServices.length > 0) {
+        throw new MER_ERR_SERVICE_RETRY_FAILED()
```
Comment (jonnydgreen) [inline lib/gateway.js:406]: Do we have enough info to infer which mandatory service failed?

**Review by jonnydgreen — COMMENTED** [review]
LGTM - just one minor comment about when mandatory services fail

File: lib/gateway.js (hunk 11 above)
Comment (sameer-coder) [reply lib/gateway.js:406]: yes we do have the service name and other info. Do you suggest we add the service name to the error message?

Comment (mcollina) [reply lib/gateway.js:406]: Let's do that, I would also attach them to a property of the error

**Review by mcollina — APPROVED** [review]
Good work @sameer-coder!!

**Review by jonnydgreen — APPROVED** [review]
LGTM - can't wait to use this!
